### ISSUE TITLE
Copying to clipboard not working

### ISSUE THREAD

**Issue by alexandre1985** [monolifed/lpcli#2]
My system is Manjaro Linux Deepin x64.

I have `xclip` installed (version 0.13-2)
My `lpcli` version is 2018.06.15-1

When I do, for example:
```
lpcli accounts.google.com myemail@gmail.com
```
my password doesn't go to clipboard and I get this message
```
Waiting for one selection request.
  Waiting for a selection request.
```

Help?

**Comment by monolifed** [comment]
When you see that message, you should be able to paste it somewhere.
It means it is waiting for your paste. And when you paste program should quit.

The command used by the program is `xclip -selection clipboard -quiet -loop 1`. You can test it: Type something after that command then press `ctrl+D` and when it says waiting you can do `ctrl+V` or paste.

**Comment by alexandre1985** [comment]
when I do:
```
echo hey | xclip -selection clipboard -quiet -loop 1
```
it copies to clipboard.
But
```
lpcli accounts.google.com myemail@gmail.com
```
it isn't copying anything to my clipboard.
I also have `clipit`installed on my Manjaro.

Can you reproduce this bug on your system?

**Comment by monolifed** [comment]
Unfortunately I couldn't reproduce it.  
It works without `clipit` as I explained in the previous post.  
Then I installed `clipit` and the program quits immediately without waiting but I can still paste and see the password in clipit's history.

Also can you test it with current code on here. There are some changes made after 2018.06.15. See [compiling](https://github.com/monolifed/lpcli#compiling) to build a binary which uses xclip.

**Comment by alexandre1985** [comment]
I found a solution.

It is not a problem of `lpcli`, but the command `xclip -selection clipboard -quiet -loop 1` doesn't work on some cases, because of my `clipit` configuration.

A way to solve this, in `lpcli`, is to change `xclip -selection clipboard -quiet -loop 1` to `xclip -selection clipboard` only.

Don't know if this modification is possible. Would solve my problem.

**Comment by monolifed** [comment]
Thanks for locating the problem.  
It is partly my fault: `-loop 1` limits the paste requests to 1 but many programs do at least 2 requests (one for the type of paste and another for the paste)  
`-quiet` keeps xclip in the foreground so you know when it quits. 
`xclip -selection clipboard` seems to be fine

**Comment by alexandre1985** [comment]
Thank you. This would solve the problem on my system (since the problem was with `xclip` command).

Look forward to test the update on my machine :wink: 

If the update doesn't resolve my problem, I will reopen this issue. Closing for now since you already have the information
